import type { CaseDefinition } from './types';

export const CASE_DEFINITIONS: CaseDefinition[] = [
  {
    id: 'case-dan-koe-value-core',
    title: 'Dan Koe：用价值内核解决差异化',
    routeId: 'content_ip',
    sceneId: 'content',
    background: '适合有多年职业经历、明确世界观和持续表达意愿的人，不适合纯搬运型内容创作。',
    trigger: '用户有经验和表达能力，但还没有把经历、观察和热爱提炼成独特的价值逻辑。',
    firstDeal: '先把价值主张挂到咨询、陪跑、研究服务或知识产品上，而不是只做空内容。',
    monetization: '通过高客单咨询、训练营、知识产品或订阅服务完成变现。',
    assetUpgrade: '把个人经历、方法论和表达风格沉淀成长线品牌资产与内容资产。',
    whyItMatches: ['强调不可替代的人性连接', '适合作为中后期差异化来源', '能解释为什么不是单纯做自媒体'],
    tags: [
      { id: 'content', label: '内容', category: 'skill' },
      { id: 'value-proposition', label: '价值主张', category: 'asset' },
      { id: 'personal-brand', label: '个人品牌', category: 'asset' },
      { id: 'mid-stage', label: '中后期', category: 'stage' },
    ],
    sourceLabel: 'Creator reference: Dan Koe',
    sourceType: 'creator_reference',
  },
  {
    id: 'case-iman-gadzhi-cashflow',
    title: 'Iman Gadzhi：先用高价值服务建立现金流',
    routeId: 'agency',
    sceneId: 'operations',
    background: '适合能直接提供结果、愿意强销售推进的人，尤其是运营、营销、增长和代理服务背景。',
    trigger: '用户纠结先做流量还是先赚钱，但当前最需要的是用高价值服务建立原始积累。',
    firstDeal: '锁定高价值赛道和一个结果导向服务，直接成交第一批精准客户。',
    monetization: '以前期高客单服务、代理费和月度 retainers 为主，而不是先追求粉丝规模。',
    assetUpgrade: '把服务案例、销售脚本和转化机制沉淀成高转化增长系统。',
    whyItMatches: ['解决现金流焦虑', '强调精准转化率', '适合作为一人企业起步期策略'],
    tags: [
      { id: 'cashflow', label: '现金流', category: 'monetization' },
      { id: 'high-ticket', label: '高客单', category: 'monetization' },
      { id: 'agency', label: '代理服务', category: 'route' },
      { id: 'early-stage', label: '起步期', category: 'stage' },
    ],
    sourceLabel: 'Creator reference: Iman Gadzhi',
    sourceType: 'creator_reference',
  },
  {
    id: 'case-justin-welsh-content-system',
    title: 'Justin Welsh：用内容系统做杠杆',
    routeId: 'training',
    sceneId: 'management',
    background: '适合已经有方法论、案例和稳定表达能力的人，不适合还没有服务验证的新手。',
    trigger: '用户已经有可输出的知识与经验，需要把内容从临时发挥升级成系统化获客。',
    firstDeal: '先围绕一个成熟主题输出内容，并把内容导向咨询、培训或数字产品。',
    monetization: '通过内容分发带来潜在客户，再承接顾问、课程、陪跑或模板产品。',
    assetUpgrade: '构建跨平台分发、复用和筛选客户的数字资产流水线。',
    whyItMatches: ['强调系统而不是勤奋', '适合作为杠杆放大器', '能连接内容与成交'],
    tags: [
      { id: 'content-system', label: '内容系统', category: 'asset' },
      { id: 'leverage', label: '杠杆', category: 'asset' },
      { id: 'training', label: '培训', category: 'route' },
      { id: 'digital-assets', label: '数字资产', category: 'asset' },
    ],
    sourceLabel: 'Creator reference: Justin Welsh',
    sourceType: 'creator_reference',
  },
  {
    id: 'case-paul-jarvis-enough-threshold',
    title: 'Paul Jarvis：定义足够，守住一人公司的边界',
    routeId: 'consulting',
    sceneId: 'management',
    background: '适合对自由度、利润率和生活质量有明确要求的人，尤其是管理岗转型者。',
    trigger: '用户容易把一人企业误解成必须持续扩张，需要重新校准成功定义。',
    firstDeal: '优先做高利润、低复杂度、边界清晰的顾问或小型服务，而不是盲目扩团队。',
    monetization: '用利润率和生活目标倒推业务规模，不把营收增长当成唯一目标。',
    assetUpgrade: '沉淀一套可持续的客户选择标准、交付边界和生活方式模型。',
    whyItMatches: ['直接回应可持续性问题', '有助于设置业务边界', '适合做长期经营原则'],
    tags: [
      { id: 'boundaries', label: '边界', category: 'style' },
      { id: 'sustainability', label: '可持续', category: 'risk' },
      { id: 'consulting', label: '顾问', category: 'route' },
      { id: 'lifestyle', label: '生活方式', category: 'style' },
    ],
    sourceLabel: 'Creator reference: Paul Jarvis',
    sourceType: 'creator_reference',
  },
  {
    id: 'case-sales-channel-service',
    title: '销售背景先做渠道代理，再升级顾问服务',
    routeId: 'channel_sales',
    sceneId: 'sales',
    background: '有 B2B 销售和渠道拓展经验，熟悉某个垂直行业的供需双方。',
    trigger: '用户已经有客户沟通、报价推进和资源整合经验，但没有产品开发能力。',
    firstDeal: '先从老客户、前同事和行业社群里拿一单撮合或代理成交，收佣金或咨询费。',
    monetization: '前期以撮合佣金和代理服务费为主，后期增加方案梳理和渠道顾问。',
    assetUpgrade: '把供需清单、话术和成交案例沉淀成渠道包和顾问模板。',
    whyItMatches: ['成交路径短', '依赖已有关系网络', '不需要先做内容或产品'],
    tags: [
      { id: 'sales', label: '销售', category: 'skill' },
      { id: 'channel', label: '渠道', category: 'route' },
      { id: 'first-deal', label: '首单', category: 'stage' },
      { id: 'relationships', label: '关系网络', category: 'asset' },
    ],
    sourceLabel: '内部知识库场景案例',
    sourceType: 'internal_pattern',
  },
  {
    id: 'case-tech-service-to-tool',
    title: '技术背景先卖自动化服务，再沉淀工具产品',
    routeId: 'tool_product',
    sceneId: 'technical',
    background: '有开发、数据处理或 AI 自动化能力，能快速做出脚本或工作流。',
    trigger: '用户技术不错，但还没有足够证据证明某个 SaaS 需求已经成立。',
    firstDeal: '先卖一个定制自动化、小工具搭建或内部提效项目，用项目费验证需求。',
    monetization: '前期收项目费，后期对高频模块做插件、模板或轻量订阅。',
    assetUpgrade: '把重复交付模块封装成工具、文档模板和复用代码。',
    whyItMatches: ['先验证需求', '交付速度快', '天然适合服务到工具的升级路径'],
    tags: [
      { id: 'technical', label: '技术', category: 'skill' },
      { id: 'automation', label: '自动化', category: 'skill' },
      { id: 'tooling', label: '工具化', category: 'asset' },
      { id: 'validation', label: '需求验证', category: 'risk' },
    ],
    sourceLabel: '内部知识库场景案例',
    sourceType: 'internal_pattern',
  },
  {
    id: 'case-ops-agency-package',
    title: '运营背景先做代执行，再升级标准化代运营',
    routeId: 'agency',
    sceneId: 'operations',
    background: '做过增长、私域、内容运营或投放优化，擅长持续执行。',
    trigger: '用户有结果记录和流程经验，但暂时不适合卖高价顾问。',
    firstDeal: '先卖一个专项代执行包，例如私域 SOP、投放优化或增长诊断。',
    monetization: '前期按项目或按月收费，后期拆成标准化套餐和陪跑方案。',
    assetUpgrade: '沉淀 SOP、周报模板、案例库和交付清单，降低边际成本。',
    whyItMatches: ['执行价值容易感知', '客户愿意先买结果', '适合形成复购'],
    tags: [
      { id: 'operations', label: '运营', category: 'skill' },
      { id: 'growth', label: '增长', category: 'skill' },
      { id: 'sop', label: 'SOP', category: 'asset' },
      { id: 'retainer', label: '月度服务', category: 'monetization' },
    ],
    sourceLabel: '内部知识库场景案例',
    sourceType: 'internal_pattern',
  },
  {
    id: 'case-design-project-to-package',
    title: '设计背景先拿项目单，再做标准化设计包',
    routeId: 'standardized_service',
    sceneId: 'design',
    background: '有视觉、品牌、页面或物料交付经验，案例展示相对清晰。',
    trigger: '用户能直接做出交付物，但内容获客和长期品牌还没建立。',
    firstDeal: '先从熟人介绍和旧合作里拿品牌页、视觉包或单页改版项目。',
    monetization: '前期按项目收费，后期升级为月度设计支持或固定设计套餐。',
    assetUpgrade: '把审美判断、模板库和交付流程沉淀成标准化服务。',
    whyItMatches: ['交付边界清晰', '客户更容易理解价值', '首单比做 IP 快'],
    tags: [
      { id: 'design', label: '设计', category: 'skill' },
      { id: 'delivery', label: '交付', category: 'route' },
      { id: 'templates', label: '模板库', category: 'asset' },
      { id: 'package', label: '套餐化', category: 'asset' },
    ],
    sourceLabel: '内部知识库场景案例',
    sourceType: 'internal_pattern',
  },
  {
    id: 'case-content-research-service',
    title: '内容背景先卖研究与选题服务，而不是直接做 IP',
    routeId: 'research_service',
    sceneId: 'content',
    background: '做过内容策划、编辑、研究或选题，表达能力强。',
    trigger: '用户会写会拆解，但还没有稳定内容转化记录。',
    firstDeal: '先卖行业研究、竞品分析、选题策划或内容诊断服务。',
    monetization: '前期卖定制报告和策划，后期做会员、数据库或专题库。',
    assetUpgrade: '把选题框架、研究资料和案例沉淀成知识库产品。',
    whyItMatches: ['先卖判断和产出', '避免空做内容', '适合积累知识资产'],
    tags: [
      { id: 'research', label: '研究', category: 'skill' },
      { id: 'topic-planning', label: '选题', category: 'asset' },
      { id: 'knowledge-base', label: '知识库', category: 'asset' },
      { id: 'report', label: '报告型变现', category: 'monetization' },
    ],
    sourceLabel: '内部知识库场景案例',
    sourceType: 'internal_pattern',
  },
  {
    id: 'case-management-consulting',
    title: '管理背景先做诊断顾问，再升级培训陪跑',
    routeId: 'consulting',
    sceneId: 'management',
    background: '做过团队管理、项目统筹或业务负责人，有一定方法论和判断。',
    trigger: '用户经验浓度高，适合卖决策和诊断，而不是卖纯执行。',
    firstDeal: '先做一次组织诊断、流程梳理或增长复盘，用低门槛顾问单切入。',
    monetization: '前期卖诊断和复盘，后期升级季度顾问、管理培训和陪跑。',
    assetUpgrade: '把框架、方法和案例沉淀成培训内容和顾问手册。',
    whyItMatches: ['判断密度高', '可卖方法而非时间', '有机会升级高客单'],
    tags: [
      { id: 'management', label: '管理', category: 'skill' },
      { id: 'diagnosis', label: '诊断', category: 'route' },
      { id: 'frameworks', label: '方法框架', category: 'asset' },
      { id: 'high-ticket', label: '高客单', category: 'monetization' },
    ],
    sourceLabel: '内部知识库场景案例',
    sourceType: 'internal_pattern',
  },
  {
    id: 'case-junior-standardized-start',
    title: '初级履历先做边界清晰的小服务',
    routeId: 'project_delivery',
    sceneId: 'junior',
    background: '经验不长，但有执行力、学习力和基础技能。',
    trigger: '用户尚未形成高密度判断，不适合一开始就卖咨询、IP 或 SaaS。',
    firstDeal: '先做一个非常小的交付，比如资料整理、页面改版、运营支持或数据清洗。',
    monetization: '前期以小单和试单建立案例，后期逐步打包成标准服务。',
    assetUpgrade: '沉淀交付模板、案例和边界，再逐渐提高客单价。',
    whyItMatches: ['风险最低', '最容易建立第一批案例', '利于后续升级'],
    tags: [
      { id: 'junior', label: '初级', category: 'stage' },
      { id: 'trial-order', label: '试单', category: 'stage' },
      { id: 'small-delivery', label: '小交付', category: 'route' },
      { id: 'case-building', label: '案例积累', category: 'asset' },
    ],
    sourceLabel: '内部知识库场景案例',
    sourceType: 'internal_pattern',
  },
];
