import type { KnowledgeArticleRef, RouteDefinition } from './types';

export const ROUTE_ARTICLES: KnowledgeArticleRef[] = [
  {
    id: 'route-project-delivery',
    title: '项目制交付',
    summary: '适合能直接输出结果、能快速定义边界和交付物的人群。',
    path: '/knowledge/routes/project-delivery',
  },
  {
    id: 'route-standardized-service',
    title: '标准化服务',
    summary: '把高频问题打包成固定范围、固定流程、固定价格的服务包。',
    path: '/knowledge/routes/standardized-service',
  },
  {
    id: 'route-consulting',
    title: '顾问咨询',
    summary: '适合经验密度高、判断能力强、能卖认知和方法的人。',
    path: '/knowledge/routes/consulting',
  },
  {
    id: 'route-agency',
    title: '代运营/代理服务',
    summary: '适合运营、增长、投放和持续执行需求明确的场景。',
    path: '/knowledge/routes/agency',
  },
  {
    id: 'route-channel-sales',
    title: '渠道销售/撮合',
    summary: '适合销售、BD、资源整合能力强，且有行业连接能力的人。',
    path: '/knowledge/routes/channel-sales',
  },
  {
    id: 'route-content-ip',
    title: '内容/IP',
    summary: '只有在表达、转化和持续输出同时成立时，才适合作为主路线。',
    path: '/knowledge/routes/content-ip',
  },
];

export const ROUTE_DEFINITIONS: RouteDefinition[] = [
  {
    id: 'project_delivery',
    name: '项目制交付',
    summary: '围绕清晰问题做一次性交付，适合设计、技术和执行型履历。',
    fitSignals: ['能直接交付结果', '有清晰案例', '容易定义边界'],
    notFitSignals: ['没有可展示样本', '完全依赖长期关系成交'],
    firstDealTemplate: '从老同事、老客户或熟人网络里找一个明确问题，用试单和小单切入。',
    upgradePath: '从单次项目升级到标准化服务包，或升级为持续顾问支持。',
    risks: ['容易重新定制', '交付时间被客户压缩'],
    recommendedArticleIds: ['route-project-delivery', 'first-deal-path'],
  },
  {
    id: 'standardized_service',
    name: '标准化服务',
    summary: '把高频问题做成固定范围、固定价格、固定流程的服务包。',
    fitSignals: ['有重复需求', '有标准动作', '能模块化交付'],
    notFitSignals: ['需求完全非标', '过度依赖个人即兴发挥'],
    firstDealTemplate: '先从一个高频痛点切一版最小服务包，再用案例和边界说明成交。',
    upgradePath: '逐步提升客单价，再沉淀成模板、课程或工具产品。',
    risks: ['定位过宽', '交付内容膨胀'],
    recommendedArticleIds: ['route-standardized-service', 'asset-pool'],
  },
  {
    id: 'consulting',
    name: '顾问咨询',
    summary: '靠行业判断和经验密度收费，适合资深从业者。',
    fitSignals: ['有决策经验', '有结果案例', '擅长诊断问题'],
    notFitSignals: ['履历偏执行', '没有独立判断记录'],
    firstDealTemplate: '以诊断、梳理和方案建议切入，而不是一上来就卖长期顾问。',
    upgradePath: '从诊断单升级到季度顾问、培训或陪跑服务。',
    risks: ['价值难展示', '没有案例时成交慢'],
    recommendedArticleIds: ['route-consulting', 'mvp-profit'],
  },
  {
    id: 'agency',
    name: '代运营/代理服务',
    summary: '适合运营、增长、投放、私域等需要持续执行的场景。',
    fitSignals: ['有持续运营经验', '能做结果复盘', '有流程意识'],
    notFitSignals: ['没有持续交付能力', '只做过零散协助'],
    firstDealTemplate: '先卖轻量代执行或专项代办，再向月度服务升级。',
    upgradePath: '从代执行升级到代运营，再沉淀 SOP、模板和工具。',
    risks: ['客户预期过高', '执行边界不清晰'],
    recommendedArticleIds: ['route-agency', 'first-deal-path'],
  },
  {
    id: 'channel_sales',
    name: '渠道销售',
    summary: '靠拿单、BD、成交和渠道资源赚钱，适合销售背景。',
    fitSignals: ['有资源网络', '有拿单经历', '擅长成交推进'],
    notFitSignals: ['没有客户触达能力', '没有关系基础'],
    firstDealTemplate: '从已认识的人脉和行业群体中找明确的供需撮合机会。',
    upgradePath: '从单次成交佣金升级为稳定代理、渠道包或顾问服务。',
    risks: ['平台依赖', '关系不可复制'],
    recommendedArticleIds: ['route-channel-sales', 'first-deal-path'],
  },
  {
    id: 'training',
    name: '培训/陪跑',
    summary: '适合有成熟方法、可教学能力和案例积累的人群。',
    fitSignals: ['做过带团队', '方法可拆解', '有明确结果'],
    notFitSignals: ['经验不稳定', '没有可复用方法'],
    firstDealTemplate: '先卖小班答疑、专项训练营或一对一陪跑，而不是直接做大课。',
    upgradePath: '从陪跑升级为训练营、课程或社群产品。',
    risks: ['交付承诺过大', '教学方法不清'],
    recommendedArticleIds: ['route-consulting', 'new-leverage'],
  },
  {
    id: 'resource_matching',
    name: '资源撮合',
    summary: '适合同时掌握供需两端信息的人，重点是撮合效率和信任。',
    fitSignals: ['有行业资源', '常做连接者', '理解供需关系'],
    notFitSignals: ['没有稳定资源池', '无法控制成交过程'],
    firstDealTemplate: '先做高匹配度的小撮合，收佣金或服务费。',
    upgradePath: '逐步做成行业情报、渠道包或社群网络。',
    risks: ['关系不可控', '议价空间有限'],
    recommendedArticleIds: ['route-channel-sales', 'asset-pool'],
  },
  {
    id: 'research_service',
    name: '信息服务/研究',
    summary: '适合内容、分析、行业研究背景，输出报告、选题或洞察产品。',
    fitSignals: ['擅长研究', '能提炼判断', '写作表达强'],
    notFitSignals: ['没有行业理解', '只有泛内容生产能力'],
    firstDealTemplate: '先卖定制研究、竞品分析或选题报告，而不是直接做订阅产品。',
    upgradePath: '从定制研究升级到行业报告、数据库或会员产品。',
    risks: ['价值感偏抽象', '复购依赖持续输出'],
    recommendedArticleIds: ['new-leverage', 'asset-pool'],
  },
  {
    id: 'tool_product',
    name: '工具产品',
    summary: '适合技术或强流程背景，把重复动作工具化。',
    fitSignals: ['技术能力强', '重复问题明显', '已有服务验证'],
    notFitSignals: ['没有真实需求验证', '想跳过服务直接做产品'],
    firstDealTemplate: '先做半定制工具或内部工具，再验证是否有人愿意付费。',
    upgradePath: '从单点工具升级到可复用插件或产品套件。',
    risks: ['容易过度开发', '真实付费需求不足'],
    recommendedArticleIds: ['new-leverage', 'mvp-profit'],
  },
  {
    id: 'vertical_saas',
    name: '垂直 SaaS',
    summary: '适合在真实服务里反复验证过痛点后，再做标准化产品。',
    fitSignals: ['有明确重复需求', '用户愿意持续付费', '已有服务样本'],
    notFitSignals: ['没有服务验证', '第一次创业就想直接做 SaaS'],
    firstDealTemplate: '先在服务里收钱，再把一部分流程产品化。',
    upgradePath: '从工具到订阅型产品，逐步降低人工比重。',
    risks: ['开发周期长', '首单太慢'],
    recommendedArticleIds: ['mvp-profit', 'new-leverage'],
  },
  {
    id: 'content_ip',
    name: '内容/IP',
    summary: '适合既能持续表达，又已经证明能转化的人。',
    fitSignals: ['持续输出', '已有成交或粉丝转化', '表达和传播强'],
    notFitSignals: ['只是想做自媒体', '没有任何商业化验证'],
    firstDealTemplate: '内容更适合作为获客放大器，先挂靠服务、咨询或陪跑产品成交。',
    upgradePath: '从内容获客升级到课程、社群、会员和品牌资产。',
    risks: ['变现慢', '容易沉迷曝光而非成交'],
    recommendedArticleIds: ['route-content-ip', 'first-deal-path'],
  },
];
