import type { KnowledgeArticleRef, SceneDefinition } from './types';

export const SCENE_ARTICLES: KnowledgeArticleRef[] = [
  {
    id: 'scene-sales',
    title: '销售背景怎么做一人企业',
    summary: '重点不是做内容，而是先从成交、BD、渠道和资源整合能力切入。',
    path: '/knowledge/scenes/sales',
  },
  {
    id: 'scene-technical',
    title: '技术背景怎么做一人企业',
    summary: '优先卖服务和工具，先用交付验证需求，再考虑产品化。',
    path: '/knowledge/scenes/technical',
  },
  {
    id: 'scene-operations',
    title: '运营背景怎么做一人企业',
    summary: '代运营、增长执行和标准化服务包通常是更短的变现路径。',
    path: '/knowledge/scenes/operations',
  },
  {
    id: 'scene-design',
    title: '设计背景怎么做一人企业',
    summary: '项目交付和标准化设计服务最容易起步，也最容易形成案例。',
    path: '/knowledge/scenes/design',
  },
  {
    id: 'scene-content',
    title: '内容背景怎么做一人企业',
    summary: '先卖研究、选题、策划或内容服务，再决定要不要走 IP 路线。',
    path: '/knowledge/scenes/content',
  },
  {
    id: 'scene-management',
    title: '管理背景怎么做一人企业',
    summary: '更适合卖判断、框架和训练，不适合一开始就重交付。',
    path: '/knowledge/scenes/management',
  },
  {
    id: 'scene-junior',
    title: '初级履历怎么做一人企业',
    summary: '先做边界清晰的小服务，先积累案例，再升级路线。',
    path: '/knowledge/scenes/junior',
  },
];

export const SCENE_DEFINITIONS: SceneDefinition[] = [
  {
    id: 'sales',
    name: '销售场景',
    summary: '以拿单、推进、渠道和关系网络为核心资产。',
    roleKeywords: ['销售', 'bd', '商务', '渠道', '客户成功'],
    skillKeywords: ['销售', '沟通', '谈判', '转化'],
    interestKeywords: ['商业', '创业'],
    primaryRoutes: ['channel_sales', 'resource_matching'],
    secondaryRoutes: ['consulting', 'standardized_service'],
    rejectedRoutes: ['content_ip'],
    reasonTemplate: '销售背景的强项通常在成交推进和资源整合，更适合先走拿单型路线，而不是先做内容表达。',
    recommendedArticleIds: ['scene-sales', 'route-channel-sales'],
  },
  {
    id: 'technical',
    name: '技术场景',
    summary: '以开发、自动化、数据和产品实现能力为核心资产。',
    roleKeywords: ['研发', '工程师', '开发', '后端', '前端', '数据', '测试工程师', '测试负责人', 'qa', '质量保障'],
    skillKeywords: ['python', 'javascript', 'sql', '自动化', '脚本', 'api', '工作流', 'agent', '测试', '测试用例', '性能测试', '弱网测试', '适配测试', 'airtest', 'unity', 'git', 'svn'],
    interestKeywords: ['技术', 'ai', '产品'],
    primaryRoutes: ['standardized_service', 'project_delivery'],
    secondaryRoutes: ['tool_product', 'vertical_saas'],
    rejectedRoutes: ['content_ip'],
    reasonTemplate: '技术背景更适合先从能交付结果的服务切入，再逐步工具化和产品化。',
    recommendedArticleIds: ['scene-technical', 'route-standardized-service'],
  },
  {
    id: 'operations',
    name: '运营场景',
    summary: '以增长、活动、私域、投放和执行流程为核心资产。',
    roleKeywords: ['运营', '增长', '市场', '投放', '用户运营', '社区运营', '新媒体运营'],
    skillKeywords: ['运营', '增长', '数据分析', '项目管理', '社区', '传播', '活动'],
    interestKeywords: ['增长', '产品'],
    primaryRoutes: ['agency', 'standardized_service'],
    secondaryRoutes: ['training', 'consulting'],
    rejectedRoutes: ['vertical_saas'],
    reasonTemplate: '运营背景天然适合代执行和标准化服务，成交路径通常比直接做产品更短。',
    recommendedArticleIds: ['scene-operations', 'route-agency'],
  },
  {
    id: 'design',
    name: '设计场景',
    summary: '以视觉、品牌、交付物和审美方案为核心资产。',
    roleKeywords: ['设计', '视觉', '品牌', 'ui', 'ux'],
    skillKeywords: ['设计', '视觉', '品牌', '物料', '排版', '海报'],
    interestKeywords: ['创作', '产品'],
    primaryRoutes: ['project_delivery', 'standardized_service'],
    secondaryRoutes: ['training', 'content_ip'],
    rejectedRoutes: ['vertical_saas'],
    reasonTemplate: '设计背景最容易卖的是清晰交付物，先拿项目和标准包，通常比直接做 IP 更稳。',
    recommendedArticleIds: ['scene-design', 'route-project-delivery'],
  },
  {
    id: 'content',
    name: '内容场景',
    summary: '以研究、写作、选题、内容策划和表达为核心资产。',
    roleKeywords: ['编辑', '写作', '新媒体', '内容运营', '内容策划', '研究', '文案', '选题'],
    skillKeywords: ['写作', '研究', '投研', '选题', '脚本撰写', '表达', '内容编辑', '文案策划'],
    interestKeywords: ['写作', '增长', '商业', 'web3'],
    primaryRoutes: ['research_service', 'standardized_service'],
    secondaryRoutes: ['agency', 'content_ip'],
    rejectedRoutes: ['vertical_saas'],
    reasonTemplate: '内容背景不等于直接做 IP，更合理的路径通常是先卖研究、策划或内容服务。',
    recommendedArticleIds: ['scene-content', 'route-content-ip'],
  },
  {
    id: 'management',
    name: '管理场景',
    summary: '以判断、组织、协调和方法论沉淀为核心资产。',
    roleKeywords: ['经理', '负责人', '总监', '咨询顾问', '项目经理'],
    skillKeywords: ['项目管理', '沟通', '产品'],
    interestKeywords: ['商业', '创业'],
    primaryRoutes: ['consulting', 'training'],
    secondaryRoutes: ['standardized_service', 'research_service'],
    rejectedRoutes: ['vertical_saas'],
    reasonTemplate: '管理背景更适合卖判断和框架，而不是一开始就做重交付或重开发产品。',
    recommendedArticleIds: ['scene-management', 'route-consulting'],
  },
  {
    id: 'junior',
    name: '初级履历场景',
    summary: '经验密度和独立判断不足时，优先做小服务和执行型交付。',
    roleKeywords: ['助理', '专员', '实习'],
    skillKeywords: ['执行', '沟通'],
    interestKeywords: ['创业', '成长'],
    primaryRoutes: ['standardized_service', 'project_delivery'],
    secondaryRoutes: ['agency'],
    rejectedRoutes: ['content_ip', 'vertical_saas', 'consulting'],
    reasonTemplate: '初级履历更适合先卖边界清晰的小服务，避免一开始就卖判断、做产品或做 IP 幻想。',
    recommendedArticleIds: ['scene-junior', 'route-standardized-service'],
  },
];
